---
- name: Configure Debian base system
  hosts: all
  become: false
  pre_tasks:
    - name: Install prerequisites for Docker repository
      apt:
        name:
          - ca-certificates
          - curl
        state: present
      become: true

    - name: Create Docker keyring directory
      file:
        path: /etc/apt/keyrings
        state: directory
        mode: '0755'
      become: true

    - name: Download Docker's GPG key
      get_url:
        url: https://download.docker.com/linux/debian/gpg
        dest: /etc/apt/keyrings/docker.asc
        mode: '0644'
      become: true

    - name: Set architecture fact
      set_fact:
        docker_arch: "{{ 'arm64' if ansible_facts['architecture'] == 'aarch64' else 'amd64' if ansible_facts['architecture'] == 'x86_64' else ansible_facts['architecture'] }}"

    - name: Add Docker repository
      apt_repository:
        repo: "deb [arch={{ docker_arch }} signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/debian {{ ansible_facts['distribution_release'] }} stable"
        state: present
        filename: docker
      become: true

    - name: Update apt cache
      apt:
        update_cache: yes
        cache_valid_time: 3600
      become: true

    - name: Upgrade all packages
      apt:
        upgrade: yes
      become: true

    - name: Install required packages
      apt:
        name:
          - build-essential
          - curl
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
          - keychain
          - neovim
          - nodejs
          - pipx
          - unzip
          - python3-pip
          - python3-pynvim
          - silversearcher-ag
          - universal-ctags
          - rsync
        state: present
      become: true

    - name: Add user to docker group
      user:
        name: "{{ lookup('env', 'USER') }}"
        groups: docker
        append: yes
      become: true

    - name: Restart docker service
      systemd:
        name: docker
        state: restarted
      become: true

    - name: Reset connection to apply group changes
      meta: reset_connection

  roles:
    - linux
