---
- name: dotfiles
  hosts: all
  tasks:
    - name: Download GitHub CLI keyring
      become: true
      shell: "curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg && sudo chmod go+r /usr/share/keyrings/githubcli-archive-keyring.gpg"
      changed_when: false
    - name: Create GitHub CLI repository configuration
      become: true
      lineinfile:
        path: /etc/apt/sources.list.d/github-cli.list
        line: "deb [arch={{ ansible_architecture }} signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main"
        create: yes
      notify: update apt cache
    - name: install the good stuff
      become: yes
      ansible.builtin.apt:
        pkg:
        - vim
        - tmux
        - rsync
        - git
        - silversearcher-ag
        - ripgrep
        - tree
        - zsh
        - keychain
        - universal-ctags
        - nodejs
        - curl
        - gh
      notify: update apt cache
    - name: fetch ohmyzsh
      ansible.builtin.get_url:
        url: https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh
        dest: /tmp/ohmyzsh-install.sh
    - name: install ohmyzsh
      ansible.builtin.shell: sh /tmp/ohmyzsh-install.sh --unattended
      args:
        creates: ~/.oh-my-zsh
    - name: make VIM dirs
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        mode: '0755'
      loop:
        - ~/.tmp/undo
        - ~/.tmp/backup
        - ~/.tmp/swap
        - ~/.tmp/fzf-history
        - ~/.local/bin
        - ~/.local/go
        - ~/.vim/autoload
    - name: copy config files into place
      ansible.posix.synchronize:
        src: files/home/
        dest: ~/
        recursive: yes
        perms: yes
        # rsync_opts:
        #   - '--ignore-existing'
    - name: setup vim-plug
      ansible.builtin.get_url:
        url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
        dest: ~/.vim/autoload/plug.vim
    - name: install vim plugins
      ansible.builtin.shell: vim +PlugInstall +qall

  handlers:
    - name: update apt cache
      become: true
      ansible.builtin.apt:
        update_cache: yes
