---
- name: dotfiles
  hosts: all
  roles:
    - role: nvim
      tags: nvim
    - role: tumbleweed
      tags: tumbleweed
    - role: files
      tags: files
    - role: python
      tags: python
    - role: services
      tags: services
    - role: symlinks
      tags: symlinks
    - role: local_utilities
      tags: local_utilities

  # tasks:
    
    # - name: Fetch ohmyzsh
    #   ansible.builtin.get_url:
    #     url: https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh
    #     dest: /tmp/ohmyzsh-install.sh
    # - name: Install ohmyzsh
    #   ansible.builtin.shell: sh /tmp/ohmyzsh-install.sh --unattended
    #   args:
    #     creates: ~/.oh-my-zsh


    # - name: Replace line in /etc/pam.d/chsh
    #   become: true
    #   ansible.builtin.lineinfile:
    #     path: /etc/pam.d/chsh
    #     regexp: '^auth\s+required\s+pam_shells.so$'
    #     line: 'auth       sufficient   pam_shells.so'
    #     backup: yes
    # - name: Change default shell to zsh
    #   become: true
    #   ansible.builtin.command: chsh -s "/usr/bin/zsh" {{ ansible_facts['user_id'] }}

    # - name: Set up kubectl
    #   become: true
    #   ansible.builtin.get_url:
    #     url: https://storage.googleapis.com/kubernetes-release/release/v1.26.4/bin/linux/amd64/kubectl
    #     dest: /usr/local/bin/kubectl
    #     mode: '0755'
