---
- name: dotfiles
  hosts: all
  tasks:
    - name: install the good stuff
      become: yes
      ansible.builtin.apt:
        pkg:
        - vim
        - tmux
        - rsync
        - git
        - silversearcher-ag
    - name: make VIM dirs
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        mode: '0755'
      loop:
        - ~/.tmp/undo
        - ~/.tmp/backup
        - ~/.tmp/swap
        - ~/.tmp/fzf-history
        - ~/.local/bin
        - ~/.local/go
    - name: copy config files into place
      ansible.posix.synchronize:
        # src: "{{ item }}"
        src: files/
        dest: ~/
        recursive: yes
        perms: yes
