---
- name: dotfiles
  hosts: all
  tasks:
    - name: install github cli keyring
      become: yes
      # copied from instructions at https://github.com/cli/cli/blob/trunk/docs/install_linux.md#debian-ubuntu-linux-raspberry-pi-os-apt
      ansible.builtin.copy:
        src: files/githubcli-archive-keyring.gpg
        dest: /usr/share/keyrings/githubcli-archive-keyring.gpg
        mode: '0644'
        owner: root
        group: root
    - name: add github cli repo
      become: yes
      ansible.builtin.apt_repository:
        repo: deb [arch=amd64 signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main
        state: present
    - name: install the good stuff
      become: yes
      ansible.builtin.apt:
        pkg:
        - vim
        - tmux
        - rsync
        - git
        - silversearcher-ag
        - gh
        - tree
        - zsh
        - keychain
    - name: fetch ohmyzsh
      ansible.builtin.get_url:
        url: https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh
        dest: /tmp/ohmyzsh-install.sh
    - name: install ohmyzsh
      ansible.builtin.shell: sh /tmp/ohmyzsh-install.sh --unattended
      args:
        creates: ~/.oh-my-zsh
    - name: make VIM dirs
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        mode: '0755'
      loop:
        - ~/.tmp/undo
        - ~/.tmp/backup
        - ~/.tmp/swap
        - ~/.tmp/fzf-history
        - ~/.local/bin
        - ~/.local/go
        - ~/.vim/autoload
    - name: copy config files into place
      ansible.posix.synchronize:
        src: files/home/
        dest: ~/
        recursive: yes
        perms: yes
        # rsync_opts:
        #   - '--ignore-existing'
    - name: setup vim-plug
      ansible.builtin.get_url:
        url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
        dest: ~/.vim/autoload/plug.vim
