---
- name: Check on existence of tools to symlink
  stat:
    path: "{{ item.src }}"
  register: result
  loop:
    - src: /usr/bin/git
      dest: ~/.local/bin/g
    - src: /usr/bin/zypper
      dest: ~/.local/bin/z
    - src: /usr/bin/kubectl
      dest: ~/.local/bin/k
    - src: /usr/bin/docker-compose
      dest: ~/.local/bin/dc

- name: Create shortcut symlinks
  ansible.builtin.file:
    src: "{{ item.item.src }}"
    dest: "{{ item.item.dest }}"
    state: link
    force: yes
  loop: "{{ result.results }}"
  when: item.stat.exists

- name: Create script symlinks
  ansible.builtin.file:
    src: "{{ item.src | realpath }}"
    dest: "{{ item.dest }}"
    state: link
    force: yes
  loop:
    - src: script/night-mode
      dest: ~/.local/bin/night-mode
    - src: script/sound
      dest: ~/.local/bin/sound
    - src: script/update_zypper_and_rkhunter
      dest: ~/.local/bin/update_zypper_and_rkhunter
    - src: script/window_manager_settings
      dest: ~/.local/bin/window_manager_settings
