---
- name: Ensure user local bin directory exists
  ansible.builtin.file:
    path: "{{ ansible_facts['env']['HOME'] }}/.local/bin"
    state: directory
    mode: '0755'

- name: Ensure user config directory exists
  ansible.builtin.file:
    path: "{{ ansible_facts['env']['HOME'] }}/.config"
    state: directory
    mode: '0755'

- name: Enable middle-click paste in GTK/Wayland
  ansible.builtin.command:
    cmd: gsettings set org.gnome.desktop.interface gtk-enable-primary-paste true
  changed_when: false
