- name: Add third party repos
  community.general.zypper_repository:
    repo: 'https://cli.github.com/packages/rpm/gh-cli.repo'
    state: present
    runrefresh: yes
  become: yes

- name: Install the required packages
  become: yes
  community.general.zypper:
    name:
    - neovim
    - tmux
    - rsync
    - git
    - the_silver_searcher
    - tree
    - zsh
    - keychain
    - universal-ctags
    - nodejs
    - curl
    - gh
    - jq
    # - yamllint

- name: Copy root config files into place
  become: yes
  ansible.posix.synchronize:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    perms: yes
  loop:
    - src: files/root/clamd.conf
      dest: /etc/clamd.conf
    - src: files/root/crontab
      dest: /etc/crontab
    - src: files/root/rkhunter.conf
      dest: /etc/rkhunter.conf
