---
dotfiles_secrets_project_name: dotfiles
dotfiles_secrets_bws_version: "2.0.0"
dotfiles_secrets_bws_server_base: ""
dotfiles_secrets_bws_path: "{{ ansible_facts['env']['HOME'] }}/.local/bin/bws"
dotfiles_secrets_bws_cache_dir: "{{ ansible_facts['env']['HOME'] }}/.cache/dotfiles/bitwarden"
dotfiles_secrets_bws_access_token_file: ""
dotfiles_secrets_bws_access_token_file_candidates:
  - "{{ ansible_facts['env']['HOME'] }}/.config/bitwarden-sm/access-token"
  - "{{ ansible_facts['env']['HOME'] }}/.config/keys/BWS_ACCESS_TOKEN"
dotfiles_secrets_bws_asset_arch_map:
  x86_64: x86_64
  amd64: x86_64
  aarch64: aarch64
  arm64: aarch64
