- name: Clone fzf
  ansible.builtin.git:
    repo: https://github.com/junegunn/fzf.git
    dest: ~/.fzf
    clone: yes
    force: yes
    depth: 1
    version: master
- name: Install fzf
  ansible.builtin.shell: ~/.fzf/install --all --no-update-rc --no-fish
- name: Download fzf-git.sh
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/junegunn/fzf-git.sh/main/fzf-git.sh
    dest: ~/.fzf-git.sh
    mode: '0644'

- name: Make VIM dirs
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
  loop:
    - ~/.tmp/undo
    - ~/.tmp/backup
    - ~/.tmp/swap
    - ~/.tmp/fzf-history
    - ~/.local/bin
    - ~/.local/go
    - ~/.local/share/nvim/site/pack/all/start
    - ~/.local/share/nvim/site/pack/all/opt
- name: Clone VIM plugins
  ansible.builtin.git:
    repo: "{{ item.repo }}"
    dest: "~/.local/share/nvim/site/pack/all/{{ item.dest }}"
    version: "{{ item.version | default('HEAD') }}"
    clone: yes
    force: no
    depth: 1
  loop:
    - repo: https://github.com/nvim-tree/nvim-tree.lua
      dest: start/nvim-tree
    - repo: https://github.com/vim-scripts/candycode.vim
      dest: start/candycode
    - repo: https://github.com/endel/vim-github-colorscheme
      dest: start/github-colorscheme
    - repo: https://github.com/NLKNguyen/papercolor-theme
      dest: start/papercolor-theme
    - repo: https://github.com/bluz71/vim-nightfly-colors
      dest: start/nightfly-colors
    - repo: https://github.com/folke/tokyonight.nvim
      dest: start/tokyonight
    - repo: https://github.com/tpope/vim-commentary
      dest: start/vim-commentary
    - repo: https://github.com/tpope/vim-surround
      dest: start/vim-surround
    - repo: https://github.com/alvan/vim-closetag
      dest: start/vim-closetag
    - repo: https://github.com/junegunn/fzf
      dest: start/fzf
      version: 0.52.1
    - repo: https://github.com/junegunn/fzf.vim
      dest: start/fzf.vim
    - repo: https://github.com/tpope/vim-fugitive
      dest: start/vim-fugitive
    - repo: https://github.com/tpope/vim-rhubarb
      dest: start/vim-rhubarb
    - repo: https://github.com/christoomey/vim-tmux-navigator
      dest: start/vim-tmux-navigator
    - repo: https://github.com/hashivim/vim-terraform
      dest: start/vim-terraform
    - repo: https://github.com/ludovicchabant/vim-gutentags
      dest: start/vim-gutentags
    - repo: https://github.com/plasticboy/vim-markdown
      dest: start/vim-markdown
    - repo: https://github.com/yasuhiroki/github-actions-yaml.vim
      dest: start/github-actions-yaml.vim
    - repo: https://github.com/github/copilot.vim
      dest: start/copilot.vim
    - repo: https://github.com/Exafunction/codeium.vim
      dest: start/codeium.vim
      # version: 289eb72
    - repo: https://github.com/dense-analysis/ale.git
      dest: start/ale
    - repo: https://github.com/madox2/vim-ai.git
      dest: start/vim-ai
    - repo: https://github.com/sindrets/diffview.nvim.git
      dest: start/diffview.nvim
    - repo: https://github.com/Vimjas/vim-python-pep8-indent.git
      dest: start/vim-python-pep8-indent
    # - repo: https://github.com/nvim-treesitter/nvim-treesitter
    #   dest: start/nvim-treesitter
    # note: opt plugins are not loaded automatically. run them with:
    #   :packadd! fooextra
    # note: if you move something here, delete it manually from start/
    #       ... and vice versa
    - repo: https://github.com/hashivim/vim-packer
      dest: opt/vim-packer
    - repo: https://github.com/hashivim/vim-vaultproject
      dest: opt/vim-vaultproject
    - repo: https://github.com/pearofducks/ansible-vim
      dest: opt/ansible-vim
    - repo: https://github.com/godlygeek/tabular
      dest: opt/tabular
    - repo: https://github.com/reedes/vim-pencil
      dest: opt/vim-pencil
    - repo: https://github.com/sindrets/diffview.nvim
      dest: opt/diffview.nvim
    # - repo: https://github.com/TheJefe/vim-prreview
    #   dest: opt/vim-prreview
    # - repo: https://github.com/pwntester/octo.nvim
    #   dest: opt/octo.nvim

