---
- name: Copy config files into place
  ansible.posix.synchronize:
    src: files/home/
    dest: ~/
    recursive: yes
    perms: yes
    rsync_opts:
      - '--itemize-changes'
    # rsync_opts:
    #   - '--ignore-existing'


- name: Ensure bashrc line exists
  ansible.builtin.lineinfile:
    path: ~/.bashrc
    line: "[ -f ~/.bashrc_jack ] && source ~/.bashrc_jack"
    state: present
